/*
 * ItemEntry.java
 *
 * Created on Apr 2, 2011, 7:29:23 PM
 */

package writingfiles;

import java.io.*;
import javax.swing.*;

public class ItemEntry extends javax.swing.JFrame {
    //  Fields
    private static FileItem fileItem = new FileItem();

    /** Creates new form ItemEntry */
    public ItemEntry()  {
        initComponents();
        try
        {  startUp();  }
        catch (Exception e)
        { }
        this.setLocation(400, 250);
        this.setTitle("Item Entry");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblItemNumber = new javax.swing.JLabel();
        txtItemNumber = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        lblCategory = new javax.swing.JLabel();
        txtCategory = new javax.swing.JTextField();
        chkHasDiscount = new javax.swing.JCheckBox();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblCost = new javax.swing.JLabel();
        txtCost = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        lblItemNumberMessage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mnuMenuBar = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Item Entry"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        lblItemNumber.setText("Item Number:");

        txtItemNumber.setToolTipText("Must be 5 digits");

        lblDescription.setText("Description:");

        lblCategory.setText("Category:");

        chkHasDiscount.setText("Has Discount");

        lblPrice.setText("Price:");

        lblCost.setText("Cost:");

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnClearActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSubmitActionPerformed(evt);
            }
        });

        lblItemNumberMessage.setText("<- Must be 5 digits");

        jLabel1.setText("<- Must be 3 digits");

        mnuFile.setText("File");

        mnuExit.setText("Exit");
        mnuExit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnuExitActionPerformed(evt);
            }
        });
        mnuFile.add(mnuExit);

        mnuMenuBar.add(mnuFile);

        setJMenuBar(mnuMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblItemNumber)
                            .addComponent(lblDescription)
                            .addComponent(lblCategory)
                            .addComponent(lblPrice)
                            .addComponent(lblCost))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtItemNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblItemNumberMessage))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtDescription, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtCategory, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel1)
                                            .addGap(114, 114, 114))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtCost, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                                .addComponent(txtPrice, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(chkHasDiscount))
                                .addComponent(btnSubmit))))
                    .addComponent(btnClear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblItemNumber)
                    .addComponent(txtItemNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblItemNumberMessage))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescription)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategory)
                    .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkHasDiscount)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrice)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCost)
                    .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnSubmit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        //  Create instance of the Item class.
        fileItem.data = new Item();

        //   Check the data.
        if(numericError(txtItemNumber.getText(),5,'I'))
        {
            txtItemNumber.selectAll();
            txtItemNumber.requestFocus();
           return;
        }
        if(numericError(txtCategory.getText(),3,'I'))
        {
            txtCategory.selectAll();
            txtCategory.requestFocus();
           return;
        }
        if(numericError(Pad.padLeft(txtPrice.getText(),6,'0'),6,'D'))
        {
            txtPrice.selectAll();
            txtPrice.requestFocus();
           return;
        }        
        if(numericError(Pad.padLeft(txtCost.getText(),6,'0'),6,'D'))
        {
            txtCost.selectAll();
            txtCost.requestFocus();
           return;
        }        

        //  Populate the Items instance fields.
        fileItem.data.setItemNumber(Integer.parseInt(txtItemNumber.getText()));
        fileItem.data.setStatus('A');
        fileItem.data.setDescription(txtDescription.getText());
        fileItem.data.setCategory(Integer.parseInt(txtCategory.getText()));
        fileItem.data.setPrice(Float.parseFloat(txtPrice.getText()));
        fileItem.data.setCost(Float.parseFloat(txtCost.getText()));
        fileItem.data.setQtyOnHand(0);
        fileItem.data.setQtyOnOrder(0);
        fileItem.data.setYtdSalesAmt(0);
        fileItem.data.setYtdSalesQty(0);
        if(chkHasDiscount.isSelected())
        {
            fileItem.data.setHasDiscount(true);
        }
        else
        {
            fileItem.data.setHasDiscount(false);
        }

        //   Write the data to the file.
        fileItem.writeRecord();
        clearScreen();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        //  Shut down the program and exit.
        try
        {  shutDown();  }
        catch (IOException e)
        { }
        System.exit(0);
    }//GEN-LAST:event_mnuExitActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        //  Clear the screen.
        clearScreen();
    }//GEN-LAST:event_btnClearActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //  Shut down the program and exit.
        try
        {  shutDown();  }
        catch (IOException e)
        { }
    }//GEN-LAST:event_formWindowClosing

    /**
    * @param args the command line arguments
    */
    public static void main(String args[])  {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemEntry().setVisible(true);
            }
        });
    }

    //  Start up processing
    public static void startUp() throws IOException
    {
        fileItem.openAppend();
        if (!fileItem.isOpen)
        {
            shutDown();
        }
    }

    //  Shut down processing
    public static void shutDown() throws IOException
    {
        //  Close files.
        if (fileItem.isOpen)
        {
            fileItem.close();
        }
        System.exit(0);
    }

    //  Clear the Screen
    public  void clearScreen()
    {
        // Clear all screen elements.
        txtItemNumber.setText("");
        txtDescription.setText("");
        txtCategory.setText("");
        txtPrice.setText("");
        txtCost.setText("");
        chkHasDiscount.setSelected(false);
        txtItemNumber.requestFocus();
    }

    //  Checks for numeric values.
    public boolean numericError(String data, int length, char type)
    {
        System.out.println("Error: " + data);
        boolean hasError = false;
        int c;

        if(data.length() == length)
        {
            for(c = 0; c < data.length(); c++)
            {
                switch (type)
                {
                    case 'I':
                        if(data.charAt(c) < '0' || data.charAt(c) > '9')
                        {
                            hasError = true;
                        }
                        break;
                    case 'D':
                        if(data.charAt(c) < '0' || data.charAt(c) > '9')
                        {
                            hasError = true;
                        }
                        if(data.charAt(c) == '.')
                        {
                            hasError = false;
                        }
                        break;
                }
            }
        }
        else
        {
            hasError = true;
        }
        return hasError;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox chkHasDiscount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblCost;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblItemNumber;
    private javax.swing.JLabel lblItemNumberMessage;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuBar mnuMenuBar;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtItemNumber;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables

}
