
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**Name: Pampered Pet
 *Date: 3.24.2018
 * @author danielcender
 * Abstract: This program allows users to select their preferences for pet boarding and see their total invoice.
 */
public class PamperedPet extends javax.swing.JFrame {

    float paymentTotal = 0f;
    String paymentMessage = "";
    float tax = 0f;
    
    /**
     * Creates new form PamperedPet
     */
    public PamperedPet() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpSuite = new javax.swing.ButtonGroup();
        grpPetType = new javax.swing.ButtonGroup();
        grpShots = new javax.swing.ButtonGroup();
        pnlSuite = new javax.swing.JPanel();
        radSuiteLarge = new javax.swing.JRadioButton();
        radSuiteXLarge = new javax.swing.JRadioButton();
        radSuiteXXLarge = new javax.swing.JRadioButton();
        radSuiteLux = new javax.swing.JRadioButton();
        pnlServices = new javax.swing.JPanel();
        chkMeds = new javax.swing.JCheckBox();
        chkBathBrush = new javax.swing.JCheckBox();
        chkWalking = new javax.swing.JCheckBox();
        chkPedicure = new javax.swing.JCheckBox();
        chkTransport = new javax.swing.JCheckBox();
        chkSundayPickup = new javax.swing.JCheckBox();
        chkFood = new javax.swing.JCheckBox();
        txtDoses = new javax.swing.JTextField();
        lblDoses = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        txtOwnerName = new javax.swing.JTextField();
        txtOwnerCell = new javax.swing.JTextField();
        txtPetAge = new javax.swing.JTextField();
        lblOwnerName = new javax.swing.JLabel();
        lblOwnerCell = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPetName = new javax.swing.JLabel();
        txtPetName = new javax.swing.JTextField();
        lblPetAge = new javax.swing.JLabel();
        pnlShots = new javax.swing.JPanel();
        radUpToDate = new javax.swing.JRadioButton();
        radNotUpToDate = new javax.swing.JRadioButton();
        lblShots = new javax.swing.JLabel();
        lblSuiteSize = new javax.swing.JLabel();
        lblServices = new javax.swing.JLabel();
        pnlType = new javax.swing.JPanel();
        radTypeCat = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        lblTypeOfPet = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        lblSpecialInstructions = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaSpecialInstructions = new javax.swing.JTextArea();
        lblStay = new javax.swing.JLabel();
        txtStay = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        pnlSuite.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        grpSuite.add(radSuiteLarge);
        radSuiteLarge.setText("Standard Large (Indoor 4' x 6'/Outdoor 4' x 12')  - $25/day");

        grpSuite.add(radSuiteXLarge);
        radSuiteXLarge.setText("Standard Extra-Large (Indoor 5' x 6'/Outdoor 5' x 12') \t\t$28.");
        radSuiteXLarge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radSuiteXLargeActionPerformed(evt);
            }
        });

        grpSuite.add(radSuiteXXLarge);
        radSuiteXXLarge.setText("Standard Double Extra Large (Indoor 8' x 6'/Outdoor 8' x 12')\t$34.00");
        radSuiteXXLarge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radSuiteXXLargeActionPerformed(evt);
            }
        });

        grpSuite.add(radSuiteLux);
        radSuiteLux.setText("Luxury Suite (Indoor 6' x 6' / Outdoor 6' x 12') \t\t\t$40.00 ");

        javax.swing.GroupLayout pnlSuiteLayout = new javax.swing.GroupLayout(pnlSuite);
        pnlSuite.setLayout(pnlSuiteLayout);
        pnlSuiteLayout.setHorizontalGroup(
            pnlSuiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuiteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSuiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radSuiteLarge)
                    .addComponent(radSuiteXLarge)
                    .addComponent(radSuiteXXLarge)
                    .addComponent(radSuiteLux))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSuiteLayout.setVerticalGroup(
            pnlSuiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuiteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radSuiteLarge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radSuiteXLarge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radSuiteXXLarge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radSuiteLux)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnlServices.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        chkMeds.setText("Delivery of medications\t\t\t\t\t\t$2.50 per dose ");

        chkBathBrush.setText("Bath & Brush\t\t\t\t\t\t\t$15.00 ");

        chkWalking.setText("Walking\t\t\t\t\t\t\t$5.00 ");

        chkPedicure.setText("Pedicure\t\t\t\t\t\t\t$10.00");

        chkTransport.setText("Transport to vet\t\t\t\t\t\t$20.00");

        chkSundayPickup.setText("Sunday pickup\t\t\t\t\t\t\t$12.50 ");

        chkFood.setText("Resort provided food\t\t\t\t\t\t$5.00 per day");

        lblDoses.setText("Doses:");

        javax.swing.GroupLayout pnlServicesLayout = new javax.swing.GroupLayout(pnlServices);
        pnlServices.setLayout(pnlServicesLayout);
        pnlServicesLayout.setHorizontalGroup(
            pnlServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServicesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlServicesLayout.createSequentialGroup()
                        .addGroup(pnlServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkFood)
                            .addComponent(chkSundayPickup)
                            .addComponent(chkTransport)
                            .addComponent(chkPedicure)
                            .addComponent(chkWalking)
                            .addComponent(chkBathBrush))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlServicesLayout.createSequentialGroup()
                        .addComponent(chkMeds)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDoses)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDoses, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        pnlServicesLayout.setVerticalGroup(
            pnlServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServicesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlServicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkMeds)
                    .addComponent(txtDoses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDoses))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkBathBrush)
                .addGap(12, 12, 12)
                .addComponent(chkWalking)
                .addGap(12, 12, 12)
                .addComponent(chkPedicure)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkTransport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkSundayPickup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkFood)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblTitle.setText("Pampered Pets Resort");

        lblOwnerName.setText("Owner Name:");

        lblOwnerCell.setText("Owner Cell:");

        lblPetName.setText("Pet's Name:");

        lblPetAge.setText("Pet's Age:");

        pnlShots.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        grpShots.add(radUpToDate);
        radUpToDate.setText("Up To Date");

        grpShots.add(radNotUpToDate);
        radNotUpToDate.setText("Not Up To Date");

        javax.swing.GroupLayout pnlShotsLayout = new javax.swing.GroupLayout(pnlShots);
        pnlShots.setLayout(pnlShotsLayout);
        pnlShotsLayout.setHorizontalGroup(
            pnlShotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShotsLayout.createSequentialGroup()
                .addGroup(pnlShotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radNotUpToDate)
                    .addComponent(radUpToDate))
                .addGap(0, 4, Short.MAX_VALUE))
        );
        pnlShotsLayout.setVerticalGroup(
            pnlShotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShotsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radUpToDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radNotUpToDate)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        lblShots.setText("Pet's Shots:");

        lblSuiteSize.setText("Suite Size:");

        lblServices.setText("Services:");

        pnlType.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        grpPetType.add(radTypeCat);
        radTypeCat.setText("Cat");

        grpPetType.add(jRadioButton2);
        jRadioButton2.setText("Dog");

        javax.swing.GroupLayout pnlTypeLayout = new javax.swing.GroupLayout(pnlType);
        pnlType.setLayout(pnlTypeLayout);
        pnlTypeLayout.setHorizontalGroup(
            pnlTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTypeLayout.createSequentialGroup()
                .addGroup(pnlTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radTypeCat)
                    .addComponent(jRadioButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTypeLayout.setVerticalGroup(
            pnlTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTypeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radTypeCat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTypeOfPet.setText("Type of Pet:");

        btnCancel.setBackground(java.awt.Color.white);
        btnCancel.setForeground(java.awt.Color.red);
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lblSpecialInstructions.setText("Special Instructions:");

        txaSpecialInstructions.setColumns(20);
        txaSpecialInstructions.setLineWrap(true);
        txaSpecialInstructions.setRows(5);
        jScrollPane1.setViewportView(txaSpecialInstructions);

        lblStay.setText("Length of Stay ( Up to 30 days):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(btnCancel)
                        .addGap(51, 51, 51)
                        .addComponent(btnSubmit)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblShots)
                                    .addComponent(lblPetAge)
                                    .addComponent(lblPetName)
                                    .addComponent(lblOwnerCell)
                                    .addComponent(lblOwnerName)
                                    .addComponent(lblTypeOfPet)
                                    .addComponent(lblSpecialInstructions))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(pnlType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtOwnerName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtOwnerCell, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPetName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPetAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pnlShots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblSuiteSize))
                                    .addComponent(lblServices, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlSuite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pnlServices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(191, 191, 191))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(lblStay)
                                .addGap(18, 18, 18)
                                .addComponent(txtStay, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblOwnerName))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtOwnerCell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblOwnerCell))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPetName)
                                    .addComponent(txtPetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPetAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPetAge))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlShots, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblShots))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTypeOfPet)
                                    .addComponent(pnlType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addComponent(lblSpecialInstructions))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(355, 355, 355)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStay)
                            .addComponent(txtStay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSuiteSize)
                            .addComponent(pnlSuite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlServices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblServices))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSubmit))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // Close out the program
        System.exit(0);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // Run calculations
        calculateInvoice();
        
        // Create formatted string
        String formattedMessage = new String();
        formattedMessage = paymentMessage;
        formattedMessage.format("|%-20d|", 70);
        
        // Display Message Dialog with Structured Message
        JOptionPane.showMessageDialog(null, formattedMessage, "Pampered Pets Invoice", JOptionPane.PLAIN_MESSAGE);
        // Set values back to zero
        paymentTotal = 0f;
        paymentMessage = "";
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void radSuiteXLargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radSuiteXLargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radSuiteXLargeActionPerformed

    private void radSuiteXXLargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radSuiteXXLargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radSuiteXXLargeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PamperedPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PamperedPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PamperedPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PamperedPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PamperedPet().setVisible(true);
            }
        });
    }
    
    // Methods go here
    public void calculateInvoice() {
        // Prep invoice message string for calculations
        paymentMessage = "\tPampered Pets Resort Invoice\n"
                + "Owner Name:\t" + txtOwnerName.getText() + "\n"
                + "Owner Cell:\t" + txtOwnerCell.getText() + "\n"
                + "Pet's Name:\t" + txtPetName.getText() + "\n"
                + "Pet's Age:\t" + txtPetAge.getText() + "\n"
                + "Pet's Shots:\t";
        
        paymentMessage += radUpToDate.isSelected() ? "Up To Date\n" : "Not Up to Date\n";
        
        paymentMessage += "Type of Pet:\t";
        
        paymentMessage += radTypeCat.isSelected() ? "Cat\n" : "Dog\n";
        
        paymentMessage += "Special Instructions:\t" + txaSpecialInstructions.getText() + "\n";
        
        // Calculate cost of room for stay
        if(radSuiteLarge.isSelected()) {
            paymentTotal += 25f * Integer.parseInt(txtStay.getText());
            paymentMessage += "Suite Choice:\tStandard Large - 25/night\n";
        }
        
        if(radSuiteXLarge.isSelected()) {
            paymentTotal += 28f * Integer.parseInt(txtStay.getText());
            paymentMessage += "Suite Choice:\tStandard Extra-Large - 28/night\n";
        }
        
        if(radSuiteXXLarge.isSelected()) {
            paymentTotal += 34f * Integer.parseInt(txtStay.getText());
            paymentMessage += "Suite Choice:\tStandard Double Extra Large - 34/night\n";
        }
        
        if(radSuiteLux.isSelected()) {
            paymentTotal += 40f * Integer.parseInt(txtStay.getText());
            paymentMessage += "Suite Choice:\tLuxury Suite - 40/night\n";
        }
        
        paymentMessage += "Extra Services:\n";
        
        // Calculate Cost of extra Services
        if(chkMeds.isSelected()) {
            paymentTotal += 2.5f * Integer.parseInt(txtDoses.getText());
            paymentMessage += "\tDelivery of Medications - " + Integer.parseInt(txtDoses.getText()) + " doses.\n";
        }
        
        if(chkBathBrush.isSelected()) {
            paymentTotal += 15;
            paymentMessage += "\tBath & Brush\n";
        }
        
        if(chkWalking.isSelected()) {
            paymentTotal += 5;
            paymentMessage += "\tWalking\n";
        }
        
        if(chkPedicure.isSelected()) {
            paymentTotal += 10;
            paymentMessage += "\tPedicure\n";
        }
        
        if(chkTransport.isSelected()) {
            paymentTotal += 20;
            paymentMessage += "\tTransport to Vet\n";
        }
        
        if(chkSundayPickup.isSelected()) {
            paymentTotal += 12.5f;
            paymentMessage += "\tSunday Pickup\n";
        }
        
        if(chkFood.isSelected()) {
            paymentTotal += 5 * Integer.parseInt(txtStay.getText());
            paymentMessage += "\tResort Provided Food - " + Integer.parseInt(txtStay.getText()) + " total.\n";
        }
        
        // Calculate Tax
        tax = paymentTotal * .08125f;
        paymentTotal += tax;
        paymentMessage += "\nTax: " + tax;
        paymentMessage += "\nTotal Invoice: " + paymentTotal;
        
        // Account for improper length of stay
        if(Integer.parseInt(txtStay.getText()) > 30) {
            paymentMessage = "You entered an invalid length of boarding stay.\n Please go back and enter in an integer up to 30. Thank you.";
        }
    }
    
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox chkBathBrush;
    private javax.swing.JCheckBox chkFood;
    private javax.swing.JCheckBox chkMeds;
    private javax.swing.JCheckBox chkPedicure;
    private javax.swing.JCheckBox chkSundayPickup;
    private javax.swing.JCheckBox chkTransport;
    private javax.swing.JCheckBox chkWalking;
    private javax.swing.ButtonGroup grpPetType;
    private javax.swing.ButtonGroup grpShots;
    private javax.swing.ButtonGroup grpSuite;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDoses;
    private javax.swing.JLabel lblOwnerCell;
    private javax.swing.JLabel lblOwnerName;
    private javax.swing.JLabel lblPetAge;
    private javax.swing.JLabel lblPetName;
    private javax.swing.JLabel lblServices;
    private javax.swing.JLabel lblShots;
    private javax.swing.JLabel lblSpecialInstructions;
    private javax.swing.JLabel lblStay;
    private javax.swing.JLabel lblSuiteSize;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTypeOfPet;
    private javax.swing.JPanel pnlServices;
    private javax.swing.JPanel pnlShots;
    private javax.swing.JPanel pnlSuite;
    private javax.swing.JPanel pnlType;
    private javax.swing.JRadioButton radNotUpToDate;
    private javax.swing.JRadioButton radSuiteLarge;
    private javax.swing.JRadioButton radSuiteLux;
    private javax.swing.JRadioButton radSuiteXLarge;
    private javax.swing.JRadioButton radSuiteXXLarge;
    private javax.swing.JRadioButton radTypeCat;
    private javax.swing.JRadioButton radUpToDate;
    private javax.swing.JTextArea txaSpecialInstructions;
    private javax.swing.JTextField txtDoses;
    private javax.swing.JTextField txtOwnerCell;
    private javax.swing.JTextField txtOwnerName;
    private javax.swing.JTextField txtPetAge;
    private javax.swing.JTextField txtPetName;
    private javax.swing.JTextField txtStay;
    // End of variables declaration//GEN-END:variables
}
