

import java.awt.*;
import javax.swing.JLayeredPane;
import java.lang.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/** Name: SalesCommissions
 * Date: 3.11.2018
 * @author danielcender
 * Abstract: This JApplet will calculate the commissions of 5 salesmen and their percentage of the whole.
 */
public class SalesCommissions extends javax.swing.JApplet {

    /**
     * Initializes the program SalesCommissions
     */
    
    //Other Necessary Variables
    //  Instance variables.s
    
    // Totals and percents
    float totalSales;
    float totalCommissions;
    
    // Each person's commissions
    float person1Commission;
    float person2Commission;
    float person3Commission;
    float person4Commission;
    float person5Commission;
    // Percent to total Commission
    float person1CommissionPercent;
    float person2CommissionPercent;
    float person3CommissionPercent;
    float person4CommissionPercent;
    float person5CommissionPercent;
    
    /*
    //Graph
    MyGraph gr;
    int p1;
    int p2;
    int p3;
    int p4;
    int p5; */
    
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesCommissions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesCommissions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesCommissions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesCommissions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /*
    //  Paint method.
    public void paint(Graphics g) {
        System.out.println("Paint");
        gr = new MyGraph(p1, p2, p3, p4, p5);
        gr.setBounds(new Rectangle(500, 10, 150, 150));
        this.add(gr);
        this.paintComponents(g);
    } */
    
    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        person1Label = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        salesLabel = new javax.swing.JLabel();
        person1NameField = new javax.swing.JTextField();
        person1SalesField = new javax.swing.JTextField();
        person2Label = new javax.swing.JLabel();
        person2NameField = new javax.swing.JTextField();
        person2SalesField = new javax.swing.JTextField();
        person3Label = new javax.swing.JLabel();
        person3NameField = new javax.swing.JTextField();
        person3SalesField = new javax.swing.JTextField();
        person4Label = new javax.swing.JLabel();
        person4NameField = new javax.swing.JTextField();
        person4SalesField = new javax.swing.JTextField();
        person5Label = new javax.swing.JLabel();
        person5NameField = new javax.swing.JTextField();
        person5SalesField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        ResultsLabel = new javax.swing.JLabel();
        commissionPercentLabel = new javax.swing.JLabel();
        person1CommissionPercentLabel = new javax.swing.JLabel();
        person2CommissionPercentLabel = new javax.swing.JLabel();
        person3CommissionPercentLabel = new javax.swing.JLabel();
        person4CommissionPercentLabel = new javax.swing.JLabel();
        person5CommissionPercentLabel = new javax.swing.JLabel();
        CommissionLabel = new javax.swing.JLabel();
        person1CommissionLabel = new javax.swing.JLabel();
        person3CommissionLabel = new javax.swing.JLabel();
        person2CommissionLabel = new javax.swing.JLabel();
        person4CommissionLabel = new javax.swing.JLabel();
        person5CommissionLabel = new javax.swing.JLabel();

        titleLabel.setText("Calculate Sales Commissions");

        person1Label.setText("Salesperson 1:");

        nameLabel.setText("Name");

        salesLabel.setText("Sales");

        person1NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                person1NameFieldActionPerformed(evt);
            }
        });

        person1SalesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                person1SalesFieldActionPerformed(evt);
            }
        });

        person2Label.setText("Salesperson 2:");

        person3Label.setText("Salesperson 3:");

        person4Label.setText("Salesperson 4:");

        person4SalesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                person4SalesFieldActionPerformed(evt);
            }
        });

        person5Label.setText("Salesperson 5:");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        ResultsLabel.setText("Results");

        commissionPercentLabel.setText("% of total");

        CommissionLabel.setText("Commission");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(person5Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(person4Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(person3Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(person2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(person1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(person1NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(person2NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(person3NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(person4NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(person5NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(submitButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(person1SalesField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(person2SalesField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(person3SalesField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(person4SalesField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(person5SalesField, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(41, 41, 41)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(person1CommissionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(person3CommissionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(person2CommissionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(person4CommissionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(person5CommissionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(salesLabel)))))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(person4CommissionPercentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(person5CommissionPercentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(person3CommissionPercentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(5, 5, 5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(person1CommissionPercentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(commissionPercentLabel)
                                            .addComponent(person2CommissionPercentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(11, 11, 11))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112)
                                .addComponent(ResultsLabel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(nameLabel)
                        .addGap(174, 174, 174)
                        .addComponent(CommissionLabel)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResultsLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(person1Label)
                            .addComponent(person1NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(person2Label)
                            .addComponent(person2NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(person3Label)
                            .addComponent(person3NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(person4Label)
                            .addComponent(person4NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(person5Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(person5NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(salesLabel)
                                    .addComponent(CommissionLabel)
                                    .addComponent(commissionPercentLabel))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(person1CommissionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(person1SalesField))
                                    .addComponent(person1CommissionPercentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(person2CommissionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(person2SalesField))
                                    .addComponent(person2CommissionPercentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(person3SalesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(person4SalesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(person3CommissionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(person3CommissionPercentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(person4CommissionPercentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(person5CommissionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(person5SalesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(person5CommissionPercentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(person4CommissionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void person1NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_person1NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_person1NameFieldActionPerformed

    private void person1SalesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_person1SalesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_person1SalesFieldActionPerformed

    private void person4SalesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_person4SalesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_person4SalesFieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // Handle all Calculations and Output
        
        // Calculate all commissions
        person1Commission = calculateCommission(Float.parseFloat(person1SalesField.getText()));
        person2Commission = calculateCommission(Float.parseFloat(person2SalesField.getText()));
        person3Commission = calculateCommission(Float.parseFloat(person3SalesField.getText()));
        person4Commission = calculateCommission(Float.parseFloat(person4SalesField.getText()));
        person5Commission = calculateCommission(Float.parseFloat(person5SalesField.getText()));
        
        // Augment commission labels
        person1CommissionLabel.setText(Float.toString(person1Commission));
        person2CommissionLabel.setText(Float.toString(person2Commission));
        person3CommissionLabel.setText(Float.toString(person3Commission));
        person4CommissionLabel.setText(Float.toString(person4Commission));
        person5CommissionLabel.setText(Float.toString(person5Commission));
       
        person1CommissionPercent = calculateCommissionPercent(person1Commission);
        person2CommissionPercent = calculateCommissionPercent(person2Commission);
        person3CommissionPercent = calculateCommissionPercent(person3Commission);
        person4CommissionPercent = calculateCommissionPercent(person4Commission);
        person5CommissionPercent = calculateCommissionPercent(person5Commission);
        
        // Calculate Percent of Individual Commissions
        person1CommissionPercentLabel.setText(Float.toString(person1CommissionPercent * 100f));
        person2CommissionPercentLabel.setText(Float.toString(100 * person2CommissionPercent));
        person3CommissionPercentLabel.setText(Float.toString(100 * person3CommissionPercent));
        person4CommissionPercentLabel.setText(Float.toString(100 * person4CommissionPercent));
        person5CommissionPercentLabel.setText(Float.toString(100 * person5CommissionPercent));
        
        // 
    }//GEN-LAST:event_submitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CommissionLabel;
    private javax.swing.JLabel ResultsLabel;
    private javax.swing.JLabel commissionPercentLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel person1CommissionLabel;
    private javax.swing.JLabel person1CommissionPercentLabel;
    private javax.swing.JLabel person1Label;
    private javax.swing.JTextField person1NameField;
    private javax.swing.JTextField person1SalesField;
    private javax.swing.JLabel person2CommissionLabel;
    private javax.swing.JLabel person2CommissionPercentLabel;
    private javax.swing.JLabel person2Label;
    private javax.swing.JTextField person2NameField;
    private javax.swing.JTextField person2SalesField;
    private javax.swing.JLabel person3CommissionLabel;
    private javax.swing.JLabel person3CommissionPercentLabel;
    private javax.swing.JLabel person3Label;
    private javax.swing.JTextField person3NameField;
    private javax.swing.JTextField person3SalesField;
    private javax.swing.JLabel person4CommissionLabel;
    private javax.swing.JLabel person4CommissionPercentLabel;
    private javax.swing.JLabel person4Label;
    private javax.swing.JTextField person4NameField;
    private javax.swing.JTextField person4SalesField;
    private javax.swing.JLabel person5CommissionLabel;
    private javax.swing.JLabel person5CommissionPercentLabel;
    private javax.swing.JLabel person5Label;
    private javax.swing.JTextField person5NameField;
    private javax.swing.JTextField person5SalesField;
    private javax.swing.JLabel salesLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables


//  Inner class for the graph.
    /*
    static class MyGraph extends JLayeredPane {
        
        private int x = 10;
        private int y = 10;
        private int w = 25;
        private int size = 100;
        int bar1;
        int bar2;
        int bar3;
        int bar4;
        int bar5;
        
        //  Constructor
        public MyGraph(int bar1, int bar2, int bar3, int bar4, int bar5) {
            this.bar1 = bar1;
            this.bar2 = bar2;
            this.bar3 = bar3;
            this.bar4 = bar4;
            this.bar5 = bar5;
        }
        
        //  Paints the graph.
        public void paintComponent(Graphics g) {
            g.setColor(Color.RED);
            g.fillRect(x, size - bar1, w, bar1);
            g.setColor(Color.BLUE);
            g.fillRect(x + w, size - bar2, w, bar2);
            g.setColor(Color.YELLOW);
            g.fillRect(x + (2*w), size - bar3, w, bar3);
            g.setColor(Color.GREEN);
            g.fillRect(x + (3*w), size - bar4, w, bar4);
            g.setColor(Color.ORANGE);
            g.fillRect(x + (3*w), size - bar5, w, bar5);
            g.drawString(String.valueOf(bar1), x, size + 20);
            g.drawString(String.valueOf(bar2), x + w, size + 20);
            g.drawString(String.valueOf(bar3), x + (2*w), size + 20);
            g.drawString(String.valueOf(bar4), x + (3*w), size + 20);
            g.drawString(String.valueOf(bar5), x + (4*w), size + 20);
        }
        
        
        
    }
*/

    
    // Method to calculate Commission
    public float calculateCommission(float sale) {
        float commission = 0;
        if(sale <= 250000) {
            commission = sale * 0.05f;
        }
        else if (sale <= 500000) {
            commission = sale * 0.07f;
        }
        else if (sale <= 750000) {
            commission = sale * 0.09f;
        }
        else {
            commission = sale * 0.12f;
        }
        totalCommissions += commission;
        return commission;
    }
    
    // Method to Calculate percent of total commissions issues
    public float calculateCommissionPercent(float c) {
        return (c / totalCommissions);
    }
}
